### ISSUE TITLE
android.hardware.camera.autofocus should not be required

### ISSUE THREAD

**Issue by tjwoon** [tjwoon/csZBar#1]
If we can remove this requirement from the AndroidManifest, we can support more devices.

Can it be done? Need to research more on android.hardware.camera.autofocus() behaviour when autofocus is not available, etc.

**Comment by tjwoon** [comment]
We should be able to safely set this feature to optional. From [Android SDK documentation](http://developer.android.com/reference/android/hardware/Camera.html#autoFocus(android.hardware.Camera.AutoFocusCallback)), `.autoFocus()` is a no-op when the device does not support it.

    If the camera does not support auto-focus, it is a no-op and onAutoFocus(boolean, Camera)
    callback will be called immediately.

**Comment by dcousens** [comment]
Was resolved in 0b114a8

**Comment by tjwoon** [comment]
Right. Forgot to close this issue... Thanks @dcousens
