### ISSUE TITLE
iOS arm64 support?

### ISSUE THREAD

**Issue by lixam** [tjwoon/csZBar#10]
Do you support 64bit on iOS. Just did a test and I am getting:

> Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_ZBarReaderViewController", referenced from:
      objc-class-ref in CsZBar.o
  "_ZBarReaderControllerResults", referenced from:
      -[CsZBar imagePickerController:didFinishPickingMediaWithInfo:] in CsZBar.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by tjwoon** [comment]
Hi there. There is some work done by other contributors related to iOS 64-bit and Simulator support - see #11 and #3. I will be merging these updates into this plugin soon

**Comment by tjwoon** [comment]
This has been fixed, thanks to @PaoloMessina's pull request #11. Please try again with v1.3.0 of this plugin.
