### ISSUE TITLE
change bg color from black to white

### ISSUE THREAD

**Issue by jayjupdhig** [tjwoon/csZBar#150]
how can i do that, i think it will give more light if we read the qr with from cam.

thx

**Comment by martijintro** [comment]
"...and other files where that key/value pair occurs are also not in GIT"

For example:

qr-code-app\platforms\android\app\src\main\res\xml\config.xml


It makes no sense if every developer needs to add that value each time and it wont be stored in GIT. That's the main problem.-

**Comment by martijintro** [comment]
or should i better check in all that things in GIT`?

**Comment by martijintro** [comment]
Maybe my question is too complex - seems so at least...

**Comment by martijintro** [comment]
No anwser is also an awswer. ;-)

Seriously: That's just ridiculous, not less and not more!! So WTF?

**Comment by martijintro** [comment]
Maybe the question is too complex, how knows??

*** LOL!! ***, *** ROFL!!! ***

**Comment by martijintro** [comment]
your product & support is crap - not more, not less!!!!!

**Comment by jayjupdhig** [comment]
problem is still pendent!!!!!!!!!!

**Comment by jayjupdhig** [comment]
Phuck csZBar - so closed. Problem solved by not-using your machework...

Thank you for your understanding.


With best regards from Switzerland,
Jan
