### ISSUE TITLE
After first QR code scan, app restarts

### ISSUE THREAD

**Issue by zhephree** [tjwoon/csZBar#17]
On iOS, I'm having this problem:

1. Launch plugin, scan a QR Code
2. Handle data from QR code, etc.
3. Launch plugin a second time
4. WebView reloads in background behind camera view
5. Scan a code, get no data because app has restarted

Any ideas?

**Comment by tjwoon** [comment]
Hi @zhephree 
What device were you using?

I am not likely to be able to test this until June, so I'll mark this as `Help Wanted` in the meantime.

**Comment by dcousens** [comment]
@zhephree if you can provide more information,  I'll re-open this bug report.  But,  using the steps you've given,  I can't reproduce this.
