### ISSUE TITLE
Congrats 

### ISSUE THREAD

**Issue by davorpeic** [tjwoon/csZBar#19]
hi @tjwoon 

I just wanted to congratulate you on this awesome plugin. I tried several other barcode scanners for cordova and they all fail or missing features! I'm using it on ios 8.3 and it works great!

thank you for your awesome work!

dp

**Comment by bau720123** [comment]
+1

**Comment by tjwoon** [comment]
Thank you @davorpeic and @bau720123
Thanks must go to @PaoloMessina and @nickgerman too, as well as other contributors :)
