### ISSUE TITLE
Can't compile on Cordova Android 5.0

### ISSUE THREAD

**Issue by bau720123** [tjwoon/csZBar#20]
I have the same problem
when I use
```
cordova plugin add org.cloudsky.cordovaplugins.zbar
cordova build android
```
it will show the error message
http://www.littlebau.com/cli/nativepagetransitions_cli.gif

I think ios maybe have the similar problem

**Comment by tjwoon** [comment]
The error in your screenshot is from `src/com/telerik/plugins/nativepagetransitions`. Please file the bug report there.

**Comment by bau720123** [comment]
hi @tjwoon 
you misunderstood
although this is a nativepagetransitions screenshot
but Zbar have the same problem too
I just use the same screenshot to tell you this issue
let me show you
http://www.littlebau.com/cli/zbar_cli.gif

**Comment by bau720123** [comment]
hi @tjwoon 
I found the true reason why I will build fail in Cordova Cli 5.0 by Android
the first one is your plugin，the second one us phonegap Official Barcode scanner plugin

```
cordova plugin add org.cloudsky.cordovaplugins.zbar
cordova plugin add https://github.com/wildabeast/BarcodeScanner.git
cordova build android
```
if you just install one of this，it will build success
but...
if you if you install all of these，the build will fail

**Comment by bau720123** [comment]
hi @tjwoon 
problem seem solved
if I use these to instead
```
cordova plugin add https://github.com/tjwoon/csZBar.git
``` 

debug and release mode all build success
