### ISSUE TITLE
Scanning is too sensitive

### ISSUE THREAD

**Issue by renerisha** [tjwoon/csZBar#21]
I'm getting barcodes from walking around with the scanner opened on android, it seems that asphalt and my carpet result in whatever pattern. The carpet has the following design (if it helps you):
![carpet](https://cloud.githubusercontent.com/assets/8925073/7583469/f13c5cf6-f895-11e4-94e5-a72c5bad2855.jpg)

Asphalt is resulting in a barcode like: 0142722651309245
The carpet returns: 0159932124100211

**Comment by jjbridges** [comment]
That's "the man" sending you subliminal messages.  :)

**Comment by tjwoon** [comment]
This is interesting :laughing: 
Will have to check if the upstream ZBar project has a known issue on this.
Thanks!

**Comment by nickgerman** [comment]
@tjwoon I am noticing this as well on newer devices, not so much older ones.  I wonder if its to do with the X_DENSITY and Y_DENSITY

**Comment by binoculars88** [comment]
@nickgerman thanks for this. Was getting some false scans too. This fix seems to work.

**Comment by dcousens** [comment]
@binoculars88 / @nickgerman can you elaborate on how you resolved this?

**Comment by nrcrabbe** [comment]
@dcousens 

Lines 147, 148 of android/ZBarScannerActivity.java

`            scanner.setConfig(0, Config.X_DENSITY, 3);`
`            scanner.setConfig(0, Config.Y_DENSITY, 3);`

Change the values 3 to 1. Fixes the false scans and I haven't had any negative issues after the change. Would be great to have these either changed to 1 (if there are no unintended consequences), or at least have it parameterised.

Cheers

**Comment by dcousens** [comment]
Thanks @nrcrabbe
