### ISSUE TITLE
How to use in Ionic Framework?

### ISSUE THREAD

**Issue by faiyazahmad** [tjwoon/csZBar#22]
I am developing a new app which require Barcode scan. I added the plugin successfully and tried to run on iOS device but could not succeeded.

**Comment by davorpeic** [comment]
Are you using actual device or trying to run it in simulator?

I'm using Ionic and csZBar and it works great. This is how I had it implemented
````
// Open scanner
// Calling from the view ng-click="openScanner()"
$scope.openScanner = function(){
    
    cloudSky.zBar.scan({
        camera: "front" // defaults to "back"
    }, function(response){
        if(response){
            alert("We got scanned!");
        }
    }, function(error){
        alert("XY Error");
    });        
    
};
````

Check your console in Safari to see if you are getting any js errors when trying to execute the plugin
davor

**Comment by feibi8597** [comment]
hi, I have a problem, if i want to use this plugin in ionic , i should inject what in controller?
