### ISSUE TITLE
[just a recommand] plugins.cordova.io will be deprecated in the near future

### ISSUE THREAD

**Issue by bau720123** [tjwoon/csZBar#24]
hi @tjwoon 

according to these
http://phonegap.com/blog/2015/05/26/npm-plugins-available/
http://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html

so...just want to inform you that your plugin should be move to npm in the future...

**Comment by tjwoon** [comment]
Noted @bau720123 . Thank you for the heads up and additional info :+1:

**Comment by bau720123** [comment]
hi @tjwoon 
just want to ask
if there is a plan that move this plugin to npm ?
thanks
