### ISSUE TITLE
Scanning two near ean

### ISSUE THREAD

**Issue by kicasta** [tjwoon/csZBar#28]
I'm working in a project, in which I need to be able to scan EANs, which are placed next to each other. I tried and modified the official phonegap plugin, which uses Zxing instead, but had problems in iOS. This however works pretty smoother in scanning small EANs in iOS, so I wanted to know, if there's a way to customize the scanning area, so it'd be just a small rectangle in the screen instead of the whole screen. 

Best Regards

**Comment by tjwoon** [comment]
Hi @kicasta. I'm not sure if we can. You can check if the upstream ZBar library which this plugin depends on supports this functionality: http://zbar.sourceforge.net/

**Comment by crissi** [comment]
zbar has scanCrop feature.

But I don't seem to be able to find the right cordinates to actually make this work correctly.


Usage:
 CGFloat x,y,w,h;
    x =0;
    y =0.25;
    w=1;
    h=0.50;

    reader.scanCrop = CGRectMake(x,y,w,h);

**Comment by cepm-nate** [comment]
The ability to change the scanning window, or at least limit the scanner to only scan along the center red line, would be very useful for me as well.

**Comment by crissi** [comment]
Check my fork, I implemented this for android and ios. I haven't gotten around to fixing it if you rotate your device while scanning though.

**Comment by cepm-nate** [comment]
Thanks. I forked your fork so I could put my own plugin name on it and do a phonegap build with it.

Looks like i might have changed the plugin name in too many places though, as it isn't loading in Android, only iOS. Android just returns 'undefined' when I run the .scan function. Not an issue for now: I'm still running the zxing plugin for android and it's working great. Sometime down the road I'll move it over to zBar as well, as it seems zBar is a bit faster.

**Comment by dcousens** [comment]
@crissi did you want to submit a PR for that feature?  It sounds very useful!

**Comment by dcousens** [comment]
Closing in favour of #61
