### ISSUE TITLE
can't build on ios8 iphone5s

### ISSUE THREAD

**Issue by DynamicLeo** [tjwoon/csZBar#3]
I really like this plugin but when I build it on ios8 iphone5s  with  a error

ld: warning: ignoring file /Users/apple/eee/platforms/ios/eee/Plugins/org.cloudsky.cordovaplugins.zbar/libzbar.a, missing required architecture x86_64 in file /Users/apple/eee/platforms/ios/eee/Plugins/org.cloudsky.cordovaplugins.zbar/libzbar.a (3 slices)
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_ZBarReaderViewController", referenced from:
      objc-class-ref in CsZBar.o
  "_ZBarReaderControllerResults", referenced from:
      -[CsZBar imagePickerController:didFinishPickingMediaWithInfo:] in CsZBar.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by botweb** [comment]
Except of commenting the lines out (to be able to hide the info Button) as @PaoloMessina mentioned, you could also replace them with the following:

```
UIView *infoButton = [[[[[self.scanReader.view.subviews objectAtIndex:2] subviews] objectAtIndex:0] subviews] objectAtIndex:3];
```

**Comment by tjwoon** [comment]
Compilation errors are now fixed for both x86_64 (Simulator) and 64-bit ARM, thanks to @PaoloMessina's pull request #11.

As mentioned by @botweb, the Info button in the iOS scanning view remains hidden.
