### ISSUE TITLE
iOS not working

### ISSUE THREAD

**Issue by mschwartz** [tjwoon/csZBar#30]
Android version works as advertised.

iOS version never calls either callback.  That is, if I scan a barcode, the scanner just goes away, doesn't call onSuccessCallback.  If I cancel, the scanner just goes away, doesn't call onFailCallback.

Using Web inspector to watch the app's console messages, I see it console.log() output a message just before calling scan().

On cancel or successful scan, I get:

[Error] SyntaxError: Unexpected EOF
	(anonymous function) (index.html, line 1)

Identical code running on android and iOS (the javascript/html/css bits).

I think there's an access violation in the ObjC code.  I'm not an ObjC guy.

Please fix this ASAP ;)

**Comment by mschwartz** [comment]
A side note, different bug, perhaps.

The Android scanner scans long bar codes, but the iOS version acts like it sees no bar code at all.

Examples:

![image](https://cloud.githubusercontent.com/assets/329637/8783383/532dcd44-2ed0-11e5-8e7f-9eb3d9ddcdaf.png)

![image](https://cloud.githubusercontent.com/assets/329637/8783390/5a8a1908-2ed0-11e5-8bac-9e1a2ddf8333.png)

**Comment by tjwoon** [comment]
@mschwartz could you post your JavaScript code which calls this plugin?

**Comment by dcousens** [comment]
@mschwartz I can't replicate this issue any where. 
If you can produce a test case, I'll happily re-open this issue.
Cheers!

**Comment by mschwartz** [comment]
It's been a long time since my client had a need for barcode scanner.  The long barcodes was their last issue with any scanner plugin they used.

I believe you that the code now works.  A lot has happened since June 2015 ;)
