### ISSUE TITLE
linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by stevekerr1** [tjwoon/csZBar#37]
I am running Xcode 7.1, and Cordova 5.3.3.  If I create a new project, inject the plugin, and attempt to compile I get the error:

linker command failed with exit code 1 (use -v to see invocation)

If I remove the plugin, it compiles fine.

**Comment by stevekerr1** [comment]
I found the solution!  'Enable Bitcode' must be set to 'no' in build options.  (don't for get to do it for both project and target)

**Comment by Frosty2** [comment]
This worked for me.  Ialso had this issue https://github.com/tjwoon/csZBar/issues/38

**Comment by jdiehl** [comment]
Thanks for the great plugin! Any chance you could update `libzbar.a` to include bitcode?

**Comment by dcousens** [comment]
Resolved in https://github.com/tjwoon/csZBar/pull/56
