### ISSUE TITLE
ReferenceError: CloudSky is not defined

### ISSUE THREAD

**Issue by ArulMozhi01** [tjwoon/csZBar#41]
Hi,
I am new to cordova. can you refer any examples or reference to add this plugin properly to the app.

**Comment by aerypton** [comment]
I have the same question!

**Comment by tjwoon** [comment]
Are you typing exactly `CloudSky`? C is supposed to be lowercase.

`cloudSky.zBar.scan(params, onSuccess, onFailure)`

**Comment by dcousens** [comment]
@ArulMozhi01 please see the [README](https://github.com/tjwoon/csZBar#api).

It clearly outlines the API such that building an example should be very simple.

``` javascript
windowcloudSky.zBar.scan({
    text_title: "OPTIONAL Title Text - default = 'Scan QR Code'", // Android only
    text_instructions: "OPTIONAL Instruction Text - default = 'Please point your camera at the QR code.'", // Android only
    camera: "front" || "back" // defaults to "back"
    flash: "on" || "off" || "auto" // defaults to "auto". See Quirks
    drawSight: true || false //defaults to true, create a red sight/line in the center of the scanner view.
}, function (text) {
  console.info('Scanned', text)
}, function (err) {
  if (err === 'cancelled') return console.info('cancelled')

  throw new Error(err)
})

**Comment by dcousens** [comment]
@tjwoon should be good to close :),  feel free to copy the example above to the README.
