### ISSUE TITLE
ZBar never closing

### ISSUE THREAD

**Issue by nbeydoon** [tjwoon/csZBar#42]
I have an issue when I try to rescan the same Qr Code, the scanner never exit but call the callback. It works good on Android but not IOS I have to click the cancel button to exit the view.

The iphone logs:
`Attempt to dismiss from view controller <MainViewController: 0x1576487a0> while a presentation or dismiss is in progress!`

**Comment by getvega** [comment]
+1

**Comment by skelletons** [comment]
+1

**Comment by wesleywesley** [comment]
+1 same issue!

**Comment by wesleywesley** [comment]
Well, I changed CsZbar.m to use this method instead; 

(probably could be improved by actually putthing the code below it in the completion handler though), but it seems to fix the issue. The previous method was deprecated (dismissModalViewControllerAnimated).

`    [self.scanReader dismissViewControllerAnimated:YES completion:nil];
`

**Comment by wesleywesley** [comment]
And also make this change in the same file: 

```
        [self.viewController presentViewController:self.scanReader animated:YES completion:nil];
        //[self.viewController presentModalViewController: self.scanReader animated: YES];

```

**Comment by nbeydoon** [comment]
Hello thanks for your help! But I don't know where I need to put this line ?

`[self.scanReader dismissViewControllerAnimated:YES completion:nil];`

**Comment by wesleywesley** [comment]
open the project in xcode and find CsZbar.m

In the methods: 
- (void)imagePickerController:(UIImagePickerController*)picker didFinishPickingMediaWithInfo:(NSDictionary*)info
- (void) imagePickerControllerDidCancel:(UIImagePickerController*)picker
- (void) readerControllerDidFailToRead:(ZBarReaderController*)reader withRetry:(BOOL)retry

Change

`    [self.scanReader dismissModalViewControllerAnimated: YES];
`

To

`    [self.scanReader dismissViewControllerAnimated:YES completion:nil];
`

You can also add

`    if ([self.scanReader isBeingDismissed]) {
        return;
    }`

to the start of each of those 3 methods.


Finally, in the scan function

- (void)scan: (CDVInvokedUrlCommand*)command;

At the very end, replace

`        [self.viewController presentModalViewController: self.scanReader animated: YES];
`

with: 

`        [self.viewController presentViewController:self.scanReader animated:YES completion:nil];
`

Let me know if this fixes the issue..

**Comment by nbeydoon** [comment]
Work like a charm ! Thanks a lot :D

**Comment by dcousens** [comment]
@wesleywesley please make this a PR :)

@tjwoon are you still working on this?
If not,  could you add contributors to help fix this?

**Comment by PedroJusto** [comment]
Thanks!!!
But after scanning several barcodes, appears alert 'Scanning failed: A scan is already in progress'
But it scans with success
