### ISSUE TITLE
QR code not scanning 10% of cases?

### ISSUE THREAD

**Issue by wesleywesley** [tjwoon/csZBar#43]
10% of cases, when you get a good clear view of the QR code, it will not scan. It's smack in the middle of the green rectangle, properly aligned yet it won't detect it.. Not moving. 

Yet when I move in the paper with the QR code on it from far, bring it closer, most of the time it will detect it. So why wouldn't it detect a completely still close-up QR code better than the moving from afar QR code?

**Comment by wesleywesley** [comment]
Oops the problem seems not to be that the QR code is not read, but that the camera view does not go away after successfully reading the QR code automatically!

**Comment by dcousens** [comment]
@wesleywesley please PR your fix :)

**Comment by dcousens** [comment]
Closing in favour of https://github.com/tjwoon/csZBar/pull/59
