### ISSUE TITLE
onSuccess called before camera activity closed

### ISSUE THREAD

**Issue by dcousens** [tjwoon/csZBar#47]
Having the camera view still running (while it is closing) AFTER the `onSuccess` callback is called means other plugins such as `cordova-plugin-dialog` won't work and have an internal violation.

This typically means I have to add a `setTimeout(..., 1000)` to my QR scanner to avoid the application from failing to re-open those plugins.

The simplest example of this would be (using `cordova-plugin-dialog`):

``` javascript
cloudSky.zBar.scan({}, function () {
  window.navigator.alert('This fails', function () {}, 'Text', 'OK')
}, functoin () {
  setTimeout(function () {
    window.navigator.alert('But this works... until you do the other one', function () {}, 'Text', 'OK')
  }, 1000)
})
```

**Comment by dcousens** [comment]
Wait,  this only happens on `iOS`... so nevermind the activity references... will re-edit issue.

**Comment by MaicolBen** [comment]
This doesn't work sometimes, I could avoid this issue removing the error callback

**Comment by dcousens** [comment]
Interesting @MaicolBen,  do you have any idea on how to fix it within the Android plugin code?

**Comment by dcousens** [comment]
If not, do you have a reproduction test-case I could use to attempt to fix it for https://github.com/tjwoon/csZBar/pull/48?

**Comment by MaicolBen** [comment]
@dcousens Nevermind, I found that onError is called before the camera activity closed in iOS and Android, so it is quite similar, but it is more related to #42
