### ISSUE TITLE
Duplicated uses-feature in AndroidManifest

### ISSUE THREAD

**Issue by MaicolBen** [tjwoon/csZBar#58]
I can't generate a build of Android because it throws the next error:

```
:mergeDebugResources
:processDebugManifest/myproject/platforms/android/AndroidManifest.xml:81:5 Error:
	Element uses-feature#android.hardware.camera at AndroidManifest.xml:81:5 duplicated with element declared at AndroidManifest.xml:80:5
myproject/platforms/android/AndroidManifest.xml:0:0 Error:
	Validation failed, exiting
 FAILED

FAILURE: Build failed with an exception.
```

I tried with commenting the `<uses-feature android:name="android.hardware.camera" />` in the plugin xml file, and it still with the same error.

**Comment by MaicolBen** [comment]
Removing and adding again android platform solves the issue

**Comment by omid-dashing** [comment]
Removing and adding again android platform
Worked for me too, thanks @MaicolBen
