### ISSUE TITLE
Customizable scan area

### ISSUE THREAD

**Issue by dcousens** [tjwoon/csZBar#61]
We should be able to customize the scan area in terms of the current orientation.
I think it is probably sane to always enforce portrait orientation of the screen to alleviate any issues of the scan area rotating.

The scanner 'sight' should reflect this area.

Related:
https://github.com/tjwoon/csZBar/issues/2
https://github.com/tjwoon/csZBar/issues/28
https://github.com/tjwoon/csZBar/issues/57

**Comment by crissi** [comment]
I could look in to this - but I would rather have someone more experienced with android/iOS take a look at it.
