### ISSUE TITLE
Camera upside down on Nexus 5X

### ISSUE THREAD

**Issue by dcousens** [tjwoon/csZBar#64]
Reference:

https://github.com/tjwoon/csZBar/issues/50#issuecomment-190244906
http://www.theverge.com/2015/11/9/9696774/google-nexus-5x-upside-down-camera

>  A Google engineer has responded to a [Reddit thread](https://www.reddit.com/r/Android/comments/3rjbo8/nexus5x_marshmallow_camera_problem/) with a curious fact; the orientation of the Nexus 5X's image sensor is somewhat unconventional, and **it's causing some problems within apps that are using Google's old (and now deprecated) camera API**. It's not a hard problem to spot, since it results in the viewfinder preview you see being flipped upside down.

**Comment by uniphonic** [comment]
I've got this bug fixed in my fork, though there are some other changes too (mostly bug fixes). Shall I just make a pull request for my entire fork?

**Comment by dcousens** [comment]
@uniphonic if your fixes are atomic in nature, sure.  But,  I don't want to just merge a blog unless we can rationale each decision made throughout?

**Comment by uniphonic** [comment]
@dcousens Yes, there are commit messages with most of them, saying what they're for.

**Comment by dcousens** [comment]
Closing in favour of #70
