### ISSUE TITLE
Example code for this plugin 

### ISSUE THREAD

**Issue by nissarcs** [tjwoon/csZBar#68]
I amnew to this please somebody help with example code for this i need to implement flash light with barcode for my project

**Comment by Pritts** [comment]
I hope this helps. Not sure if this is what you're asking for
```
var params = {
    text_title: "Title Text'", // Android only
    text_instructions: "Introduction text" // Android Only
    camera: "back" // Either "front" or "back"
    flash: "on" // defaults to "auto"
    drawSight: true //defaults to true, create a red sight/line in the center of the scanner view.
};

var onSuccess = function (success) {
    // Successful return after scan
};

var onFailure = function(failure) {
    //code for failure
};

cloudSky.zBar.scan(params, onSuccess, onFailure);

```

**Comment by nissarcs** [comment]
Thanks i wanted flash screeen has to be open while barcode started and lights off when bar code scan finishes. So i fixed that if any body wants the code i can provide

**Comment by dcousens** [comment]
@nissarcs you're always better off just posting it for that 1 person that might find it several months from now.

**Comment by nissarcs** [comment]
In ZBarScannerActivity.java class replace the below code with 
           
           Camera.Parameters p = camera.getParameters();
            p.setFlashMode(Camera.Parameters.FLASH_MODE_TORCH);
            camera.setParameters(p);
            camera.startPreview();

comment or remove above code and add 
 camParams.setFlashMode(Camera.Parameters.FLASH_MODE_TORCH);

because flash will pops up and goes so if you want light should be on through out the scan you have to add Torch thanks for support

**Comment by dcousens** [comment]
You should be able to enable the flash/torch in JS...
