### ISSUE TITLE
Does it work with cordova 4.0+?

### ISSUE THREAD

**Issue by guizero** [tjwoon/csZBar#7]
I was using scandit barcode scanner. But it stopped working with cordova 4.0+. I have installed yours and I can open the scanner, but I after the scan, it goes back to the app, showing no result. My code is:

cloudSky.zBar.scan("",
                     function (s) {
                         alert(s);
                     }, 
                     function (s) {
                         alert("Scanning failed: " + s);
                     }

**Comment by tjwoon** [comment]
Hi again. Sorry for the long delay between replies... I just tried the plugin with cordova-android@3.5.0 on an emulator and an Android 5.0.1 device - it works as expected in both cases (failure callback on emulator of course).

I don't know what versions of Cordova you are referring to. Each component of Cordova has an independent version number now. The latest version of cordova-android is 3.6.4, which works fine for me too. Meanwhile the command line tools are at version 4.1.2, which is what I am using.

**Comment by guizero** [comment]
I was having a problem with my emulator and my device. This error no longer
exists. Thank you

**Comment by tjwoon** [comment]
I see. Thanks for the update :)
