### ISSUE TITLE
plugin.xml does not define android namespace

### ISSUE THREAD

**Issue by arzig** [tjwoon/csZBar#71]
The following namespace should be in the plugin element

xmlns:android="http://schemas.android.com/apk/res/android"

**Comment by dcousens** [comment]
Why should this be there?

**Comment by arzig** [comment]
Because the attributes for uses-feature and others use the namespace android which is an undefined prefix. It works based on however Cordova does merging for android manifest.xml but on its own I believe this is not technically a valid document.
