### ISSUE TITLE
I got 404 when I install  org.cloudsky.cordovaplugins.zbar,

### ISSUE THREAD

**Issue by zrh123** [tjwoon/csZBar#75]
cordova plugins add org.cloudsky.cordovaplugins.zbar
Error: Registry returned 404 for GET on https://registry.npmjs.org/org.cloudsky.cordova
plugins.zbar

**Comment by jjbridges** [comment]
Try the updated path for cloudsky:
cordova plugin add cordova-plugin-cszbar
