### ISSUE TITLE
[iOS 10] Application crashes immediately after trying to scan a barcode

### ISSUE THREAD

**Issue by eladmoshe** [tjwoon/csZBar#77]
When running Cordova app with the plugin on iOS 10 device, the application crashes as soon as the plugin is used:
``` 
2016-07-28 15:53:20.569989 HelloCordova[383:42510] *** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSRangeException> *** -[__NSArrayM objectAtIndex:]: index 3 beyond bounds [0 .. 1]
2016-07-28 15:53:20.571153 HelloCordova[383:42572] [access] <private>
```

I created a [project](https://github.com/eladmoshe/cordova-barcode-ios10) that has only "HelloCordova" default template and the plugin. To test just tap the "scan barcode" button.
I tested with the following devices:
* iOS 9.3.2 real device (MD297HB/A) - works as expected.
* iOS 10.0 Beta real device (ME440HB/A) - The app crashes after tapping the scan barcode button
* iOS 9.3.2 simulator - opens the camera simulation correctly
* iOS 10.0 simulator immediately fails (although the application doesn't crash).

**Comment by dcousens** [comment]
The only `index:3` I can find in this project is here: https://github.com/tjwoon/csZBar/blob/843b432d5601662585ea16ef576a2a65474c0c73/ios/CsZBar.m#L89

@eladmoshe could you try putting some error checking around that line and see if it still occurs?

**Comment by eladmoshe** [comment]
@dcousens indeed this is the code that throws the error. Commenting out those two lines fixes the issue:
```c
// Hack to hide the bottom bar's Info button... originally based on http://stackoverflow.com/a/16353530
UIView *infoButton = [[[[[self.scanReader.view.subviews objectAtIndex:2] subviews] objectAtIndex:0] subviews] objectAtIndex:3];
[infoButton setHidden:YES];
```

I added a breakpoint and evaluated the expression in both iOS10 and iOS9

*iOS 10:*
```
(lldb) po [[[[self.scanReader.view.subviews objectAtIndex:2] subviews] objectAtIndex:0] subviews] 
<__NSArrayM 0x600000048ee0>(
<UIToolbarTextButton: 0x7f94ab513130; frame = (0 0; 53 54); opaque = NO; layer = <CALayer: 0x6000000391c0>>,
<UIButton: 0x7f94ab5122b0; frame = (298 16; 22 22); opaque = NO; layer = <CALayer: 0x600000038fc0>>
)
```

*iOS 9:*
```
(lldb) (lldb) po [[[[self.scanReader.view.subviews objectAtIndex:2] subviews] objectAtIndex:0] subviews] 
<__NSArrayM 0x7fc46385ced0>(
<_UIToolbarBackground: 0x7fc46257b1e0; frame = (0 0; 320 54); autoresize = W; userInteractionEnabled = NO; layer = <CALayer: 0x7fc4625749a0>>,
<UIImageView: 0x7fc46257b3b0; frame = (0 -0.333333; 320 0.333333); autoresize = W+BM; userInteractionEnabled = NO; layer = <CALayer: 0x7fc462572dd0>>,
<UIToolbarTextButton: 0x7fc46385b1e0; frame = (0 0; 52.6667 54); opaque = NO; layer = <CALayer: 0x7fc4638591c0>>,
<UIButton: 0x7fc46385aa50; frame = (298 16; 22 22); opaque = NO; layer = <CALayer: 0x7fc463841bc0>>
)
```

Hope this helps. Thanks!

**Comment by eladmoshe** [comment]
Changing the last `objectAtIndex:` from `3` to `1` on iOS 10 works, so I assume that adding a simple check for OS version >= 10 will fix the issue.
I can create a pull request tomorrow.

**Comment by dcousens** [comment]
Thanks a tonne @eladmoshe :+1:

**Comment by dcousens** [comment]
Fixed in #78

**Comment by SuThwe** [comment]
@eladmoshe You saved my day :D
Thank you so much :)

**Comment by niezw** [comment]
@eladmoshe crash on iOS 11,what can i do ? please ...

`*** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSRangeException> *** -[__NSArrayM objectAtIndex:]: index 1 beyond bounds [0 .. 0]`

**Comment by eladmoshe** [comment]
@niezw we moved to use the official Cordova [plugin](https://github.com/phonegap/phonegap-plugin-barcodescanner) .
The native ZBar library is not maintained for years. The official library uses ZXing, which is better in every way, and I can't find any reason to use ZBar now. 
The migration is very easy, hope this helps...

**Comment by niezw** [comment]
@eladmoshe thanks....

**Comment by lukeisontheroad** [comment]
@niezw I had to use the following: cordova plugin add https://github.com/AndreasGassmann/csZBar.git#hide-info-button-ios11 --save --nofetch

**Comment by b1ueRa1n** [comment]
@lukeisontheroad  thanks, It's work for me.
