### ISSUE TITLE
Red line overlay and Code 128 limiter

### ISSUE THREAD

**Issue by redphyre** [tjwoon/csZBar#8]
Hey, this isn't exactly an issue but I couldn't find a way to just message you.

I'm looking to modify this slightly but everything I've seen with zBar SDK online doesn't match what exists in this repo. I'm wanting to add a vertical centered red line overlay to the scanner and also limit it to only read Code 128. How can I do this?

Thank you so much for your time spent working on this, it will really help my business once everything is flushed out in my app.

Matthew Walker

**Comment by tjwoon** [comment]
Hi Matthew. On iOS my plugin uses the ZBar library's built in View/Controller `self.scanReader = [ZBarReaderViewController new];`. Please refer to line 43 of the file [CsZBar.m](https://github.com/redphyre/csZBar/blob/master/ios/CsZBar.m).

As to how to modify the appearance, I guess you would have to hack the View after displaying it. I had to hack it to simplify the footer bar too...

**Comment by PaoloMessina** [comment]
@redphyre 
Hi, try my pull request that contains a possible solution for the color sight:

https://github.com/tjwoon/csZBar/pull/11#issuecomment-73707900

**Comment by tjwoon** [comment]
Hi @redphyre, the red line has been added thanks to @PaoloMessina's pull request #11. The line is horizontal on Android as we have optional title and instruction texts at the top and bottom of the view.

No updates on your request to limit scanning to Code 128 as yet...

**Comment by wesleywesley** [comment]
See here how to limit scanning to a specific type: https://github.com/tjwoon/csZBar/issues/46
