### ISSUE TITLE
iOS 10 failure

### ISSUE THREAD

**Issue by cagedagain** [tjwoon/csZBar#81]
There appears to be an issue when running this on iOS10 (using a 5s) where the scanner fails to open. The first request will ask for the camera permissions but the scanner fails to open at all. A second request will fail as the scanner is 'already open'.

**Comment by uniphonic** [comment]
I just ran into this as well. It crashes when run on an iPhone 5s under iOS 10.

**Comment by cagedagain** [comment]
This is also occurring on the iPad Pro 9.7

**Comment by arnebjorgan** [comment]
Same issue on iPhone 6 with iOS 10

**Comment by cagedagain** [comment]
Discovered that the issue was down to the info button index having changed in iOS 10 which was fixed in commit 894cb50d7fa232cdda5b19420fa6c1fae9922a8c. It turns out that this repo and the npm package are misaligned. Adding the plugin directly from the repo has fixed the issue.

**Comment by dcousens** [comment]
https://github.com/tjwoon/csZBar/issues/70
