### ISSUE TITLE
iOS 10

### ISSUE THREAD

**Issue by nbeydoon** [tjwoon/csZBar#82]
Hi, since I have updated my phone to iOS 10 the scanner does not open anymore.  Can you please help with this ? I need help I'm not good enough to patch the iOS part of the code myself and I have more than 100 customers on my application.

**Comment by dcousens** [comment]
@nbeydoon have you tried the version currently in this repository? Or only via `npm`?

**Comment by mindr242** [comment]
Having the same problem. I am pulling from npm via phonegap build. Can you please push the IOS 10 fix to npm.

**Comment by jdogresorg** [comment]
I am also having the same problem pulling from npm via phonegap build. I have 3 applications which use this plugin and users are starting to complain. Can you please push the fix for IOS 10 to npm so that phonegap build starts using the fix?

**Comment by dcousens** [comment]
I won't be able to do this today,  can you not specify the repository URL in phonegap?

**Comment by jdogresorg** [comment]
http://docs.phonegap.com/phonegap-build/configuring/plugins/#plugin-source

Should be able to specify the repo... I'll give it a try. You think you will be able to get to updating npm this week?

**Comment by dcousens** [comment]
> You think you will be able to get to updating npm this week?

Its definitely part of a plan,  its just a matter of priorities if other things come up first.

**Comment by dcousens** [comment]
Closing in favour of https://github.com/tjwoon/csZBar/issues/70
