### ISSUE TITLE
I got issue in IOS 10.0

### ISSUE THREAD

**Issue by rajasbc** [tjwoon/csZBar#85]
WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSRangeException> *** -[__NSArrayM objectAtIndex:

Camera not opening in IOS 10.0 +

**Comment by dtmp** [comment]
Hello rajasbc, i have had same error and successfully resolved it with reinstall this plugin by the following command:

cordova plugin add https://github.com/tjwoon/csZBar

(more info in issue "Installation problem #84")

**Comment by rajasbc** [comment]
Error fixed thanks a lot Dtmp . Great
