### ISSUE TITLE
Hangs on iOS (latest) @ Oct 2016  // A scan is already in progress

### ISSUE THREAD

**Issue by ullfindsmit** [tjwoon/csZBar#87]
The most recent build via phonegap build is not loading the scanner for iOS only
It works fine on Android

On second attempt, it says 
A scan is already in progress

Please help

**Comment by cepm-nate** [comment]
I am seeing the same thing too, and it's a pity as czbar is the fastest scanner I've found for iOS.

**Comment by dcousens** [comment]
Have you pulled the latest version from this repository?

**Comment by ullfindsmit** [comment]
I am using phonegap build which pulls directly

**Comment by cepm-nate** [comment]
I was using a branch of it to limit scanning to just the red line (useful when there are many 1D barcodes close together) but have switched to the official phonegap-plugin-barcode scanner (with  jlowe234's branch) as it seems to be updated a little more frequently, and limits scanning to just along the red line.

Thanks for all the work dcousens! I'll check back occasionally to see if there's a way to limit the scanning rectangle for both iOS and Android. :-)

**Comment by gitlovenotwar** [comment]
I had the same issue. It asks to open the camera but the camera did not show, and opening scanner again returns error with "A scan is already in progress".

**Comment by Thamodharank** [comment]
Hello All,

I too face the same problem for the recent build. 

In iOS, the scanner does not open and throws the "A scan is already in progress" for the second time.

Did anyone find a solution?

**Comment by ullfindsmit** [comment]
Here is a little more details from console log within XCode

2016-10-21 15:15:36.221162 MyApp[722:139008] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2016-10-21 15:15:36.228703 MyApp[722:139008] [MC] Reading from public effective user settings.
2016-10-21 15:15:36.304453 MyApp[722:139008] *** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSRangeException> *** -[__NSArrayM objectAtIndex:]: index 3 beyond bounds [0 .. 1]

**Comment by nrcrabbe** [comment]
Here's how I got around it.

`ionic plugin rm cordova-plugin-cszbar`
`ionic plugin add https://github.com/tjwoon/csZBar.git#master`

(use `cordova plugin ...` if not using ionic)

The npm release won't be new enough so you'll need to fall back to the git repository

HTH

**Comment by ullfindsmit** [comment]
```
phonegap plugin rm cordova-plugin-cszbar
phonegap plugin add https://github.com/tjwoon/csZBar.git#master
phonegap platform remove ios
phonegap platform add ios
```


Did the trick

**Comment by gitlovenotwar** [comment]
@nrcrabbe This really works, nice! Thanks!!!
