### ISSUE TITLE
iOS scanning returns result as null

### ISSUE THREAD

**Issue by Thamodharank** [tjwoon/csZBar#88]
Hello,

I have implemented the csZBar barcode scanner using https://github.com/aNkM/csZBar.git.

It works fine in android. I get the scan code properly on success.

But in iOS the scanned data is returned as undefined value in the success function. Not only the text, format also returned as undefined in the success object. 
(i.e) 
function onSuccess(result){
alert(result.text); // returns undefined
alert(result.format); // returns undefined
}

Is there any special permissions I need to give for iOS version?

Thanks in advance.

**Comment by dcousens** [comment]
Did you ever resolve this @Thamodharank?

**Comment by Thamodharank** [comment]
Hello,

Yes I resolve this by re install the plugin using https://github.com/tjwoon/csZBar.git#master.

It seems the aNkM repository does not have iOS support.

Thanks.

**Comment by dcousens** [comment]
Related to #70

**Comment by dcousens** [comment]
Thanks for the follow up @Thamodharank
