### ISSUE TITLE
ios10 make scanner run under background?

### ISSUE THREAD

**Issue by picassohoang** [tjwoon/csZBar#90]
I have installed the latest version of this plugin 1.3.2 and try to run on ios10. It seems cloudSky.zBar.scan(params, onSuccess, onFailure) start the camera screen silently (under the cordova webview). Nothing happen until I tap on home button and then return to the app then the scanner show up.

**Comment by picassohoang** [comment]
<meta http-equiv="Content-Security-Policy" content="**default-src *;** script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; media-src *;">

The 'default-src *;' in the meta tag of index.html cause this issue. No idea why.

**Comment by dcousens** [comment]
Thanks for the follow up @picassohoang

**Comment by dcousens** [comment]
What did you change that to @picassohoang ?

**Comment by picassohoang** [comment]
I remove 'default-src *;' and the meta tag becomes: `<meta http-equiv="Content-Security-Policy" content="script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; media-src *;">`

The old meta tag can run on ios <=v9.3 but has issue with ios v10
