### ISSUE TITLE
"Scan failed due to an error" error on iOS and Android

### ISSUE THREAD

**Issue by itsallrelative** [tjwoon/csZBar#92]
Getting a generic error when trying to scan on both my iOS and Android versions of my ionic app. The error just says: 

Here is the code I have implemented:

`$scope.scanBarcode = function () {
		try {

			cloudSky.zBar.scan({
				drawSight: true,
				flash: "off"
			}, function (scanData) {

				$scope.amazonAPICall(scanData);

			}, function (err) {
				$ionicPopup.alert({
					title: 'Scan Error',
					template: err
				});
			});

		} catch (err) {

			$ionicPopup.alert({
				title: 'Something went wrong',
				template: 'Please try your scan again. ' + err
			});

		}
	};`

The only other information I get is a small stacktrace from xcode: 

`2016-11-09 19:39:57.167419 Ninja Scan[4791:1389736] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2016-11-09 19:39:57.174636 Ninja Scan[4791:1389736] [MC] Reading from public effective user settings.
2016-11-09 19:39:57.242854 Ninja Scan[4791:1389736] *** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSRangeException> *** -[__NSArrayM objectAtIndex:]: index 3 beyond bounds [0 .. 1]
`

**Comment by dcousens** [comment]
@itsallrelative have you tried the latest code in this repository?

**Comment by itsallrelative** [comment]
I have 1.3.1 installed, which is what pulled down from the repo about 30 minutes ago.

**Comment by dcousens** [comment]
@itsallrelative this may be an issue external to this library.

But,  just to be sure,  could you play with https://github.com/tjwoon/csZBar/blob/31e2eda04b45f9e00651c26de5661756d7605782/ios/CsZBar.m#L81,  try some hard-coded indices and see if your issue is reproduced consistently?

What happens on your Android application?

**Comment by dcousens** [comment]
You might also want to try submitting this to the cordova team.

**Comment by itsallrelative** [comment]
Figured out how to resolve by following this issue: https://github.com/tjwoon/csZBar/issues/87

Had to do:

`ionic plugin rm cordova-plugin-cszbar
ionic plugin add https://github.com/tjwoon/csZBar.git#master`

**Comment by dcousens** [comment]
Awesome,  thanks @itsallrelative
