### ISSUE TITLE
iOS 10.1.1 - decidePolicyForNavigationAction - Error when calling cloudSky.zBar.scan

### ISSUE THREAD

**Issue by harish441** [tjwoon/csZBar#97]
Hello,

I am new to Cordova iOS development. In one of my application, I started using csZBar and works charmingly until I updated my iOS to 10.1.1. After the update, on clicking the method **cloudSky.zBar.scan**, I am getting the below error:

**WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSRangeException> *** -[__NSArrayM objectAtIndex:]: index 3 beyond bounds [0 .. 1]**

Request you all to help me in fix this issue and make the plugin compatible with new iOS update.

Thanks
Harish Kalla

**Comment by dcousens** [comment]
https://github.com/tjwoon/csZBar/issues/70

**Comment by harish441** [comment]
Fixed the issue in CsZBar.m by applying the below changes as suggested in http://stackoverflow.com/questions/16353491/how-to-hide-info-button-in-zbar-bar-code-reader-for-ios6-0-and-above/16353530#16353530 by Kiko:

float currentVersion = 5.1;
float sysVersion = [[[UIDevice currentDevice] systemVersion] floatValue];
UIView * infoButton;

if (sysVersion > currentVersion && sysVersion < 10 )
   infoButton = [[[[[self.scanReader.view.subviews objectAtIndex:2] subviews] objectAtIndex:0] subviews] objectAtIndex:3];
else
   infoButton = [[[[[self.scanReader.view.subviews objectAtIndex:2] subviews] objectAtIndex:0] subviews] objectAtIndex:1];

[infoButton setHidden:YES];

**Comment by dcousens** [comment]
Hi @harish441, as pointed out in #70,  if you just use the latest code in this repository (not what is released on npm),  it already has the fix necessary.

Cheers

**Comment by harish441** [comment]
@dcousens: Thanks for the update. I retrieved the latest code in the repository and it's working pretty good.

**Comment by harish441** [comment]
@dcousens , @tjwoon : One question, may be weird. As I am new to GitHub, I don't know where to place this request. 

Are you guys planning to have iOS development to be done in Swift in near future?

**Comment by dcousens** [comment]
@harish441 this module isn't in active development, mostly just maintenance.  So I'd say it would be safe to say that Swift isn't in scope at this time.
